language: java

env:
  matrix:
    - TARGET_PLATFORM=indigo
    - TARGET_PLATFORM=juno
    - TARGET_PLATFORM=kepler
    - TARGET_PLATFORM=luna

before_script:
  - Xvfb :99 -ac -screen 0 1024x768x24 &
  - export DISPLAY=:99.0

script: mvn -e --file me.gladwell.m2e.test/pom.xml -Dtarget.platform=$TARGET_PLATFORM -Dtycho.showEclipseLog=true verify
