env:
  matrix:
    - TARGET_PLATFORM=indigo
    - TARGET_PLATFORM=juno
    - TARGET_PLATFORM=kepler
    - TARGET_PLATFORM=luna

before_script:
  - sudo apt-get update
  - echo yes | sudo apt-get install python-software-properties
  - echo yes | sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update
  - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  - echo debconf shared/accepted-oracle-license-v1-1 seen true |  sudo debconf-set-selections
  - echo yes | sudo apt-get install --force-yes oracle-java7-installer
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0

script: mvn -e --file me.gladwell.m2e.test/pom.xml -Dtarget.platform=$TARGET_PLATFORM -Dtycho.showEclipseLog=true verify
